In [1]:
import pandas as pd
import numpy as np

import re

from sqlalchemy import create_engine
import psycopg2

from config import password

import time

In [2]:
engine = create_engine(f'postgresql://postgres:{password}@database-1.cwp515opznhz.us-west-1.rds.amazonaws.com:5432/postgres')

In [3]:
train_df = pd.read_csv("train.csv")
train_df.columns = [x.lower() for x in train_df.columns]

train_df.head()

,id,mssubclass,mszoning,lotfrontage,lotarea,street,alley,lotshape,landcontour,utilities,...,poolarea,poolqc,fence,miscfeature,miscval,mosold,yrsold,saletype,salecondition,saleprice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [ ]:
train_df.to_sql(name='train', con=engine, if_exists='append' , index=False)